services:
  server:
    build: 
      context: ./server
    volumes:
      - ./server:/app
    working_dir: /app
    depends_on:
      - db
    env_file:
      - .env.dev
    ports:
        - '8000:8000'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    command: ./mvnw spring-boot:run

#  ui:
#    build:
#      context: ./ui
#    depends_on:
#      - server
#    ports:
#      - '5173:5173'
#    volumes:
#      - ./ui:/app
#      - /app/node_modules
#    environment:
#      - HOST=0.0.0.0
#      - CHOKIDAR_USEPOLLING=true
#      - WATCHPACK_POLLING=true
#    command: npm run dev -- --host 0.0.0.0 --port 5173 --watch

  db:
    image: 'postgres:15'
    ports:
      - '5432:5432'
    env_file:
      - .env.dev
    volumes:
      - db_data_dev:/var/lib/postgresql/data


volumes:
  db_data_dev:
  db_data:


