services:
  postgres-dev:
    image: postgres:16-alpine
    container_name: pm-postgres-dev
    environment:
      POSTGRES_DB: ${DEV_DB_NAME}
      POSTGRES_USER: ${DEV_DB_USER}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
      - ../scripts/database-init/setup-database.sh:/docker-entrypoint-initdb.d/setup-database.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DEV_DB_USER} -d ${DEV_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    container_name: pm-backend
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-dev:5432/${DEV_DB_NAME}?currentSchema=personal_manager
      SPRING_DATASOURCE_USERNAME: ${DEV_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DEV_DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      postgres-dev:
        condition: service_healthy
    volumes:
      - ../backend:/app
    working_dir: /app
    command: ./mvnw spring-boot:run

volumes:
  postgres-dev-data:
  postgres-test-data:
